language: erlang
sudo: false
otp_release:
  - 21.2
  - 21.1
  - 20.3
  - 19.3
  - 18.3
  - 17.5
before_script:
  - kerl list installations
install:
  - rebar get-deps
#  - wget --directory-prefix=deps http://dist.neo4j.org/neo4j-community-3.5.0-unix.tar.gz
#  - tar xzf deps/neo4j-community-3.5.0-unix.tar.gz -C deps
#  - export ERBI_TEMPDB_BIN_NEO4J="$(pwd)/deps/neo4j-community-3.5.0/bin"
