language: erlang
sudo: false
otp_release:
  - 21.1
  - 20.0
  - 19.0
  - 18.1
  - 17.5
  - R16B02
  - R16B01
  - R15B03
  - R15B02
#  - R15B01 lacks port_info(Port,os_pid);
before_script:
  - kerl list installations
install:
  - rebar get-deps
  - wget --directory-prefix=deps http://dist.neo4j.org/neo4j-community-2.0.0-unix.tar.gz
  - tar xzf deps/neo4j-community-2.0.0-unix.tar.gz -C deps
  - export ERBI_TEMPDB_BIN_NEO4J="$(pwd)/deps/neo4j-community-2.0.0/bin"
